### ISSUE TITLE
Is this repo still maintained? 

### ISSUE THREAD

**Issue by yotam707** [sequelize/sequelize-typescript#1452]
# Issue
There are a lot of issues and problems that need to be addressed if @RobinBuschmann is not available maybe offer this repo to someone else who would want to take charge of maintaining it.

**Comment by WikiRik** [comment]
Hi @yotam707 

Development on `sequelize-typescript` is indeed slowing down. Luckily `sequelize-typescript` will be merged with `sequelize` for the next major release (v7) under the NPM package [`@sequelize/core`](https://www.npmjs.com/package/@sequelize/core)

This will be lead by @ephys so I'll give her the chance to explain the plans further.

**Comment by ephys** [comment]
That is pretty much it :)
sequelize-typescript is being sunsetted because we're merging it into core.
This should be easier to manage for our small team.
It'll be available in V7. It'll mostly be a copy/paste to begin with but we do have plans to slowly replace some APIs with alternatives we think would work better.

**Comment by WikiRik** [comment]
Yes, a new version should come out within the next few days
