### ISSUE TITLE
sequelize.sync() is missing from the documentation

### ISSUE THREAD

**Issue by DavidA94** [sequelize/sequelize-typescript#480]
So, I've figured out based on the [example](https://github.com/RobinBuschmann/sequelize-typescript-example/blob/master/lib/server.ts) that in order to use my database, I have to call `sequelize.sync();` However, I don't see anything about this call in the README, which seems to be the only documentation.

Since I'm just starting with sequelize, I was not familiar with that call. Can it be added somewhere to the docs with a link back to the [full docs](https://sequelize.readthedocs.io/en/latest/api/sequelize/#sync) on it?

**Comment by RobinBuschmann** [comment]
Hey @DavidA94, in general an ORM is not responsible for setting up the tables in a database - it is up to you. Anyway, sequelize provides a method to get your database ready, which is `sync` as you already mentioned. But `sync` should not be used for production. Use database migrations instead. One tool I currently use is https://github.com/db-migrate/node-db-migrate.

But to ask your actual question: sequelize-typescript is only a wrapper for sequelize and since sequelize does have documentation regarding `sync`(http://docs.sequelizejs.com/) we should try to prevent redundant documentation. So I recommend to also check the original sequelize docs, when using sequelize-typescript.

Hope this helps

**Comment by DavidA94** [comment]
Hi @RobinBuschmann,

If sync shouldn't be used in production, then how do I initialize the database? I don't need it to set up my database, as that is initialized with SQL scripts (which I find easier to work with than db-migrate's syntax).

Thanks,
David

**Comment by DavidA94** [comment]
So, I just need to do an `await new Sequelize`. gotcha.

Thanks!

**Comment by RobinBuschmann** [comment]
> So, I just need to do an await new Sequelize(...). gotcha.

yes! :)
